spring:
  jpa:
    database: h2
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type: trace
        generate_statistics: trace
