spring:
  data:
    mongodb:
      authentication-database: admin
      database: test
      host: mongo
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type: trace
        generate_statistics: trace
